name: Bob the Builder

# Run on all branches, including all pull requests, except the 'dev'
# branch since that's where we run Coverity Scan (limited tokens/day)
on:
  push:
    branches:
      - '**'
      - '!dev'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    # Verify we can build on latest Ubuntu with both gcc and clang
    name: ${{ matrix.compiler }}
    strategy:
      matrix:
        compiler: [gcc, clang]
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      MAKEFLAGS: -j3
      CC: ${{ matrix.compiler }}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          make
      - name: Install Check
        run: |
          make install DESTDIR=/tmp/pev
          ls -lR /tmp/pev
